docker_image: "docker.io/123c/hexlet"
docker_tag: "latest"
container_name: "bulletin-board"
app_port: "8080"
management_port: "9090"
app_data_dir: "/opt/bulletin-board/data"
app_logs_dir: "/opt/bulletin-board/logs"
app_environment:
  SPRING_PROFILES_ACTIVE: "dev"
  # SPRING_DATASOURCE_URL: "{{ vault_db_url }}"
  # SPRING_DATASOURCE_USERNAME: "{{ vault_db_user }}"
  # SPRING_DATASOURCE_PASSWORD: "{{ vault_db_password }}"
